language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq doxygen

install:
    - pip install -r dev-requirements.txt
    - pip install python-coveralls

script:
    - pip install -e .
    - ci/build

after_success:
    coveralls
